catalago_de_filmes/cat_filmes/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from rest_framework import routers
from .api.viewsets import FilmeViewSet

router = routers.DefaultRouter()
router.register('api_filmes', FilmeViewSet)

urlpatterns = [
    path('', views.index, name='index'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('deletar/<int:id>', views.deletar, name='deletar'),
    path('api_filmes/', include(router.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalago_de_filmes/cat_filmes/models.py
from django.db import models

class Filme(models.Model):
    GENERO_CHOICES = (
        # No choice você segue o mesmo padrao ex: duas letras maisculas vão ser sempre maiusculas ex: três letras maiusculas sempre será três letras maiusculas # choiches podem ser feitos com dicionarios
        ('AC', 'Ação'),
        ('AV', 'Aventura'),
        ('RO', 'Romance'),
        ('TE', 'Terror'),
        ('DR', 'Drama'),
        ('SU', 'Suspense'),
        ('FC', 'Ficção Cientifica'),
        ('CD', 'Comedia'),
        ('DO', 'Documentario'),
        ('AN', 'Animação'),
        ('NS', 'Não Selecionado'),
    )
    
    titulo = models.CharField(max_length=100)
    diretor = models.CharField(max_length=60)
    sinopse = models.TextField()
    ano_lancamento = models.DateField()
    duracao = models.IntegerField(default=0)
    genero = models.CharField(max_length=2, choices=GENERO_CHOICES, default='NS')
    data_cad = models.DateTimeField(auto_now_add=True)
    imagem = models.ImageField(upload_to='capas', null=True, blank=True)

    def __str__(self):
        return self.titulo
    

catalago_de_filmes/cat_filmes/forms.py
from django import forms   
from .models import Filme

class FilmeForm(forms.ModelForm):
    class Meta:
        model = Filme
        fields = '__all__'
    

catalago_de_filmes/cat_filmes/views.py
from django.shortcuts import render, redirect
from .models import Filme
from django.contrib import messages
from .forms import FilmeForm

def index(request):
    filmes = Filme.objects.all()
    return render(request, 'cat_filmes/index.html', {'filmes' : filmes})

def cadastro(request):
    if request.method == 'POST':
        form = FilmeForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Filme Cadastrado com Sucesso!')
            form = FilmeForm()
        else:
            messages.error(request, 'Erro ao Salvar o Filme!')
    else:
        form = FilmeForm()
    return render(request, 'cat_filmes/cadastro.html', {'form' : form })

def deletar(request, id):
    deleteme = Filme.objects.get(id=id)
    if request.method == 'POST':
        deleteme.delete()
        return redirect('/')
    return render(request, 'cat_filmes/deletar.html')
    

catalago_de_filmes/cat_filmes/templates/cat_filmes/cadastro.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciador de Filmes</title>
    {% bootstrap_css %}
</head>
<body>
    <div class="container">
        <h2>Cadastro de Filmes</h2>
        <a href="{% url 'index' %}">INDEX</a>
        {% bootstrap_messages %}
        <form action="{% url 'cadastro' %}" method="post" class="form" autocomplete="off" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            {% endbuttons %}
        </form>
    </div>
    {% bootstrap_javascript %}
</body>
</html>

catalago_de_filmes/cat_filmes/templates/cat_filmes/deletar.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciador de Filmes - DELETAR </title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        Você tem certeza que deseja deletar?
        <input type="submit">
    </form>
</body>
</html>

catalago_de_filmes/cat_filmes/templates/cat_filmes/index.html
{% load static %}
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciador de Filmes</title>
    {% bootstrap_css %}
</head>
<body>
    <div class="container">
        <a href="{% url 'cadastro' %}">Cadastrar Filme</a>
        <div class="row">
            {% for filme in filmes %}
            <div class="col">
                <img src="media/{{ filme.imagem }}" class="img-thumbnail" alt="Capa do Filme">
                <h2>Titulo: {{ filme.titulo }}</h2>
                <h3>Diretor: {{ filme.diretor }}</h3>
                <p>Sinopse: {{ filme.sinopse}}</p>
                <span>Ano de lançamento: {{ filme.ano_lancamento }}</span><br>
                <span>Duração: {{ filme.duracao }}</span><br>
                <span>Genero: {{ filme.get_genero_display }}</span><br>
                <a class="btn btn-danger" href="{% url 'deletar' filme.id %}">Deletar Filme</a>
            </div>
            {% endfor %}
        </div>
    </div>
    {% bootstrap_javascript %}
</body>
</html>