clinica_rosto_corpo/rosto_corpo_gerenciamento_consultas/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from rest_framework import routers
from .api.viewsets import ConsultaViewSet

router = routers.DefaultRouter()
router.register('api_consultas', ConsultaViewSet)

urlpatterns = [
    path('', views.index, name='index'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('deletar/<int:id>', views.deletar, name='deletar'),
    path('api_consultas/', include(router.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clinica_rosto_corpo/rosto_corpo_gerenciamento_consultas/models.py
from django.db import models

class Consulta(models.Model):
    DIA_CONSULTA_CHOICES = (
        ('DOM', 'Domingo'),
        ('SEG', 'Segunda'),
        ('TER', 'Terça'),
        ('QUA', 'Quarta'),
        ('QUI', 'Quinta'),
        ('SEX', 'Sexta'),
        ('SAB', 'Sabado'),
    )

    nome_paciente = models.CharField(max_length=150)
    idade = models.IntegerField(default=0)
    cpf = models.CharField(max_length=30)
    data_nascimento = models.DateField()
    dia_consulta = models.CharField(max_length=3, choices=DIA_CONSULTA_CHOICES, default='DOM')
    imagem = models.ImageField(upload_to='fotos')
    hora_marcada = models.DateTimeField()
    processo_agendado = models.TextField()

    def __str__(self):
        return self.nome_paciente

clinica_rosto_corpo/rosto_corpo_gerenciamento_consultas/forms.py
from django import forms   
from .models import Consulta

class ConsultaForm(forms.ModelForm):
    class Meta:
        model = Consulta
        fields = '__all__'
    

clinica_rosto_corpo/rosto_corpo_gerenciamento_consultas/views.py
from django.shortcuts import render, redirect
from .models import Consulta
from django.contrib import messages
from .forms import ConsultaForm

def index(request):
    consultas = Consulta.objects.all()
    return render(request, 'rosto_corpo_gerenciamento_consultas/index.html', {'consultas' : consultas})

def cadastro(request):
    if request.method == 'POST':
        form = ConsultaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Consulta Cadastrada com Sucesso!')
            form = ConsultaForm()
        else:
            messages.error(request, 'Erro ao Salvar Consulta!')
    else:
        form = ConsultaForm()
    return render(request, 'rosto_corpo_gerenciamento_consultas/cadastro.html', {'form' : form })

def deletar(request, id):
    deleteme = Consulta.objects.get(id=id)
    if request.method == 'POST':
        deleteme.delete()
        return redirect('/')
    return render(request, 'rosto_corpo_gerenciamento_consultas/deletar.html')
    

clinica_rosto_corpo/rosto_corpo_gerenciamento_consultas/templates/rosto_corpo_gerenciamento_consultas/cadastro.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciador de Consultas</title>
    {% bootstrap_css %}
</head>
<body>
    <div class="container">
        <h2>Cadastro de Consultas</h2>
        <a href="{% url 'index' %}">INDEX</a>
        {% bootstrap_messages %}
        <form action="{% url 'cadastro' %}" method="post" class="form" autocomplete="off" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            {% endbuttons %}
        </form>
    </div>
    {% bootstrap_javascript %}
</body>
</html>

clinica_rosto_corpo/rosto_corpo_gerenciamento_consultas/templates/rosto_corpo_gerenciamento_consultas/deletar.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciador de Consultas - DELETAR </title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        Você tem certeza que deseja deletar?
        <input type="submit">
    </form>
</body>
</html>

clinica_rosto_corpo/rosto_corpo_gerenciamento_consultas/templates/rosto_corpo_gerenciamento_consultas/index.html
{% load static %}
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consultas Rosto & Corpo</title>
    {% bootstrap_css %}
</head>
<body>
    <div class="container">
        <a href="{% url 'cadastro' %}">Cadastrar Consulta</a>
        <div class="row">
            {% for consulta in consultas %}
            <div class="col">
                <img src="media/{{ consulta.imagem }}" class="img-thumbnail" alt="Capa da consulta" style="width= 300px; heigth= 300px;">
                <h2>Nome do Paciente: {{ consulta.nome_paciente }}</h2>
                <p>Idade do Paciente: {{ consulta.idade }} anos</p>
                <p>Data de Nascimento: {{  consulta.data_nascimento }}</p>
                <p>Processo agendado para: {{ consulta.processo_agendado }}</p>
                <span>Consulta marcada para: {{ consulta.get_dia_consulta_display }}</span><br>
                <span>Horario da consulta: {{ consulta.hora_marcada }}</span>
                <a class="btn btn-danger" href="{% url 'deletar' consulta.id %}">Deletar consulta</a>
            </div>
            {% endfor %}
        </div>
    </div>
    {% bootstrap_javascript %}
</body>
</html>