projeto_agenda/agendas/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from rest_framework import routers
from .api.viewsets import AgendaViewSet

router = routers.DefaultRouter()
router.register('api_agendas', AgendaViewSet)

urlpatterns = [
    path('', views.index, name='index'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('deletar/<int:id>', views.deletar, name='deletar'),
    path('api_agendas/', include(router.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projeto_agenda/agendas/models.py
from django.db import models

class Agenda(models.Model):
    DIAS_CHOICES =  (
        ('DOM', 'Domingo'),
        ('SEG', 'Segunda'),
        ('TER', 'Terça'),
        ('QUA', 'Quarta'),
        ('QUI', 'Quinta'),
        ('SEX', 'Sexta'),
        ('SAB', 'Sabado'),
    )

    disciplina = models.CharField(max_length=100)
    assunto = models.TextField()
    tempo_estudado = models.IntegerField(default=0)
    dia_semana = models.CharField(max_length=3, choices=DIAS_CHOICES, default='DOM')
    foto = models.ImageField(upload_to='assuntos')

    def __str__(self):
        return self.disciplina

projeto_agenda/agendas/forms.py
from django import forms   
from .models import Agenda

class AgendaForm(forms.ModelForm):
    class Meta:
        model = Agenda
        fields = '__all__'
    

projeto_agenda/agendas/views.py
from django.shortcuts import render, redirect
from .models import Agenda
from django.contrib import messages
from .forms import AgendaForm

def index(request):
    agendas = Agenda.objects.all()
    return render(request, 'agendas/index.html', {'agendas' : agendas })

def cadastro(request):
    if request.method == 'POST':
        form = AgendaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Agenda cadastrada com sucesso!')
            form = AgendaForm()
        else:
            messages.error(request, 'Erro ao salvar agenda!')
    else:
        form = AgendaForm()
    return render(request, 'agendas/cadastro.html', {'form' : form })

def deletar(request, id):
    deleteme = Agenda.objects.get(id=id)
    if request.method == 'POST':
        deleteme.delete()
        return redirect('/')
    return render(request, 'agendas/deletar.html')

projeto_agenda/agendas/templates/agendas/cadastro.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciador de Agenda</title>
    {% bootstrap_css %}
</head>
<body>
    <div class="container">
        <h2>Cadastro de Agendas</h2>
        <a href="{% url 'index' %}">INDEX</a>
        {% bootstrap_messages %}
        <form action="{% url 'cadastro' %}" method="post" class="form" autocomplete="off" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            {% endbuttons %}
        </form>
    </div>
    {% bootstrap_javascript %}
</body>
</html>

projeto_agenda/agendas/templates/agendas/deletar.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciador de Agendas - DELETAR </title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        Você tem certeza que deseja deletar?
        <input type="submit">
    </form>
</body>
</html>

projeto_agenda/agendas/templates/agendas/index.html
{% load static %}
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agenda - Lista</title>
    {% bootstrap_css %}
</head>
<body>
    <div class="container">
        <a href="{% url 'cadastro' %}">Cadastrar Agenda</a>
        <div class="row">
            {% for agenda in agendas %}
            <div class="col">
                <img src="media/{{ agenda.foto }}" class="img-thumbnail" alt="Capa da Agenda" style="width= 300px; heigth= 300px;">
                <h2>Disciplina: {{ agenda.disciplina }}</h2>
                <h3>Assunto: {{ agenda.assunto }}</h3>
                <p>Tempo de Estudo: {{  agenda.tempo_estudado }}</p>
                <span>Dias: {{ agenda.get_dia_semana_display }}</span><br>
                <a class="btn btn-danger" href="{% url 'deletar' agenda.id %}">Deletar Agenda</a>
            </div>
            {% endfor %}
        </div>
    </div>
    {% bootstrap_javascript %}
</body>
</html>